services:
  hacking1:
    image: selenium/node-chrome:4.15.0
    container_name: hacking1
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
    ports:
      - "5555:4444"
    volumes:
      - /home/tristan/Documents/browser-profiles/profiles/hacking1/downloads:/home/seluser/Downloads
    networks:
      - browser-net

networks:
  browser-net:
    external: true
    name: browser-profiles_browser-net
